import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    'docs/gettingstarted',
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: ['docs/guides/slow-transaction'],
    },
    {
      type: 'category',
      label: 'Features',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'docs/features/features' },
      items: [
        'docs/features/timeline',
        'docs/features/governor-limits-heap',
        'docs/features/calltree',
        'docs/features/analysis',
        'docs/features/database',
        'docs/features/inspector',
        'docs/features/find',
        'docs/features/raw-log',
      ],
    },
    'docs/settings',
    {
      type: 'category',
      label: 'Ecosystem',
      collapsible: true,
      collapsed: false,
      items: [
        'docs/features/mcp',
        {
          type: 'link',
          label: 'Apex Log Parser',
          href: 'https://github.com/apex-dev-tools/apex-log-parser',
        },
      ],
    },
  ],

  communitySidebar: [{ type: 'autogenerated', dirName: 'community' }],
};

export default sidebars;
