blank_issues_enabled: false
contact_links:
  - name: Report a bug
    url: https://github.com/forcedotcom/salesforcedx-vscode/issues/new/choose
    about: Please report Apex Log Analyzer bugs in the Salesforce VS Code repository.
  - name: Feature request
    url: https://github.com/forcedotcom/debug-log-analyzer/discussions/new?category=ideas
    about: Feature requests should be opened as discussions.
