name: CI

on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]
  workflow_dispatch:

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install Packages
        run: HUSKY=0 pnpm install
      - name: Lint Files
        run: pnpm run lint

  tests:
    name: Run Log-viewer Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install Packages
        run: HUSKY=0 pnpm install
      - name: Tests
        run: |
          pnpm run test:ci

  build:
    name: Verify VSCode Package Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install vsce
        run: pnpm add --global @vscode/vsce
      - name: Install Dependencies
        run: |
          HUSKY=0 pnpm install
      - name: Build VSCode Package
        run: |
          cd lana
          vsce package --no-dependencies
