name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Packages
        run: npm ci
      - name: Lint Files
        run: npm run lint

  tests:
    name: Run Log-viewer Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Packages
        run: npm ci
      - name: Tests
        run: |
          cd log-viewer
          npm run test:ci
