name: Optimize Images
on:
  push:
    branches:
      - main
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'certinia'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: 9sako6/imgcmp@96250a4f33dd989ab6cd28096e854309e3c17227 # v2.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths-ignore-regexp: 'node_modules/.*'
